language: node_js

node_js:
    - "10"
    - "12"
    - "13"
    - "13"

stages:
    - acceptance_test

job_acceptance_test:
    stage: acceptance_test
    if: branch = master
    script:
        - "yarn install"
        - "yarn test"